---
# tasks file for docker

- name: Install apt-transport-https
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

  #- name: Add signing key
  #  ansible.builtin.apt_key:
  #  url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  #  state: present

- name: Add signing key
  #  ansible.builtin.apt_key:
  #  url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  #  state: present
  shell: 'curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'  

  #- name: Add repository into sources list
  #  ansible.builtin.apt_repository:
  #  repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  #  state: present
  #  filename: docker

- name: Add repository into sources list
  #  ansible.builtin.apt_repository:
  #  repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  #  state: present
  #  filename: docker
  shell: 'echo "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable" | tee /etc/apt/sources.list.d/docker.list'

- name: Install Docker & Docker Compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
        #- docker-compose
        #      - docker-registry
    state: latest
    update_cache: true
