apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin.rentahouse-rolebinding
  namespace: rentahouse
subjects:
- kind: User
  name: admin.rentahouse
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin.rentahouse-role
  apiGroup: rbac.authorization.k8s.io

