apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rentahouse
  name: admin.rentahouse-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
