---
# tasks file for Kubernetes

- name: Install apt-transport-https
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: Add signing key
  ansible.builtin.apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    keyring: "/usr/share/keyrings/kubernetes-archive-keyring.gpg"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes


# Configuration du daemon Docker : rotation des logs


# Créer le fichier /etc/modules-load.d/k8s.conf
# Relancer les modules


# Créer le fichier /etc/sysctl.d/99-kubernetes.conf 
# Relancer sysctl

- copy:
    src: 
    dest: 
    owner: root
    group: root
  register: result

- shell: sysctl -p --system
  become: yes
  when: result.changed


# Install kubernetes components

- name: Install kubernetes components
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest
    update_cache: true

