apiVersion: apps/v1
kind: Deployment
metadata:
  name: wshabitation-deployment
  namespace: rentahouse
spec:
  selector:
    matchLabels:
      app: wshabitation
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wshabitation
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
      - name: wshabitation
        image: registry.gitlab.com/kilroywashere.devops/wshabitation/main
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "gcpproxy"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 120
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 120
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "50Mi"
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL Auth Proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          - "--private-ip"
          # Enable structured logging with LogEntry format:
          - "--structured-logs"
          # Replace DB_PORT with the port the proxy should listen on
          - "--port=3306"
          - "rentahouse-instance"
        securityContext:
          # The default Cloud SQL Auth Proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
