apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: rentahouse-gateway
  namespace: rentahouse
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.rah.kube.kilroy.devops.lan"
