version: '3.9'

services:
  apache-php:
    build: ./phpredis/
    # image: phpredis:7.4
    container_name: phpredis
    ports:
     - 8091:80
    networks:
      - lampredis-network

  mysql:
    image: mariadb:10.7
    container_name: mariadbng
    hostname: mariadb
    env_file: ./mariadb/.env
    ports:
      - 3376:3306
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lampredis-network

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    networks:
      - lampredis-network

networks:
  lampredis-network:
    driver: bridge
