---
# tasks file for apachephp

- name: "Upgrade all packages"
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

#1. Cette tâche permet d’installer Apache (apache2) à l’aide du module apt
- name: "Install the latest version of Apache"
  ansible.builtin.apt:
    name: apache2
    state: latest
  become: true

- name: "Ajout du groupe apache a l'utilisateur ec2-user"
  ansible.builtin.user:
    name: admin
    groups: www-data
    append: yes
  become: true

#2. Cette tâche active le service Apache
- name: "apache service activation"
  service:
    name: apache2
    state: started
    enabled: yes
  become: true

#3. Cette tâche fait appel à un autre fichier de configuration pour installer PHP. Elle est exécutée uniquement
# si la variable php_install est à vraie (par défaut, elle est à faux)
- include_tasks: "php-install.yaml"
  when: php_install|default(False)|bool

- name: "Restart Apache"
  service:
    name: apache2
    state: restarted
  become: true
