apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rentahouse-pvc
  namespace: rentahouse
  labels:
    app.kubernetes.io/name: rentahouse-wslocation
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
