apiVersion: v1
kind: Service
metadata:
  name: wslocation-service
  namespace: rentahouse
spec:
  selector: 
    app: wslocation
  type: NodePort  
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: "LoadBalancer"