---

- name: "mediawiki database"
  community.mysql.mysql_db:
    name: "{{mediawiki_db_name}}"
    state: present

- name: "mediawiki user and privileges"
  community.mysql.mysql_user:
    name: "{{mediawiki_db_user}}"
    password: "{{mediawiki_db_password}}"
    priv: "{{mediawiki_db_name}}.*:ALL"
    host: "%"
    state: "present"

# Pour les hosts, on peut désigner tous les hôtes du groupes webserver :
#   host: "{{item}}"
#   state: "present"
#   loop: "{{ groups['webservers'] }}"
