apiVersion: apps/v1
kind: Deployment
metadata:
  name: wslocation-deployment
  namespace: rentahouse
  labels:
    app.kubernetes.io/component: web-service
    app.kubernetes.io/part-of: rentahouse
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-stack
    jobLabel: wslocation
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: wslocation
  replicas: 1
  template:
    metadata:
      labels:
        app: wslocation
        app.kubernetes.io/component: metrics
        app.kubernetes.io/instance: prometheus-stack
        jobLabel: wslocation
        release: prometheus-stack
    spec:
      volumes:
      - name: host-mapped-nfs
        hostPath:
          path: "/share/nfs/rentahouse/wslocation/logs"
      containers:
      - name: wslocation
        image: registry.gitlab.com/kilroywashere.devops/wslocation/main
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "preprod"
        ports:
        - containerPort: 8080
        volumeMounts:
            # name must match the volume name above
            - name: host-mapped-nfs
              mountPath: "/app/logs"
