apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rentahouse
  name: nfs-rentahouse-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
