apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wslocation-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  endpoints:
    - path: /metrics
      interval: 60s
      port: wslocation-metrics
      scheme: http
      scrapeTimeout: 14s
  namespaceSelector:
    matchNames: [rentahouse]
  selector:
    matchLabels:
      app: wslocation-service

