resource "aws_iam_user" "terraform" {
  name = var.aws_terraform_username

  tags = {
    Name        = "Terraform user for backend"
    Environment = "development"
  }
}

resource "aws_iam_access_key" "terraform" {
  user = aws_iam_user.terraform.name
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "terraform-aws-connection" {
  content = <<-DOC
    # AWS User connection
    # Generated by Terraform mgmt configuration.

    export AWS_ACCESS_KEY_ID="${aws_iam_access_key.terraform.id}"
    export AWS_SECRET_ACCESS_KEY="${aws_iam_access_key.terraform.secret}"
    DOC
  filename = "terraform-aws-connection.txt"
}