apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: docker-server-x
  namespace: monitoring
spec:
  #  scrapeInterval: 5s
  staticConfigs:
  - targets:
    - '192.168.1.12:9100'
    - '192.168.1.13:9100'
    - '192.168.1.14:9100'

