apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: nginx-proxy
  namespace: monitoring
spec:
  metricsPath: "/metrics"
  staticConfigs:
  - targets:
    - '192.168.1.7:9113'

