apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata: 
  name: hpa-wslocuser
  namespace: rentahouse
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: hpa-wslocuser 
  minReplicas: 1 
  maxReplicas: 3
  metrics: 
    - type: Resource 
      resource: 
        name: cpu 
        target: 
          type: AverageValue 
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 120
      - type: Pods
        value: 2
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      policies:
      - type: Percent
        value: 40
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max