apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wslocuser-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  endpoints:
    - path: /actuator/prometheus
      interval: 60s
      port: wslocuser-metrics
      scheme: http
      scrapeTimeout: 14s
  namespaceSelector:
    matchNames: [rentahouse]
  selector:
    matchLabels:
      app: wslocuser-service

