apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: monitoring
spec:
  selector: 
    app.kubernetes.io/name: alertmanager
  type: NodePort  
  ports:
    - name: http-web
      port: 9093
      targetPort: 9093 
      nodePort: 30093

