apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector: 
    app.kubernetes.io/name: grafana
  type: NodePort  
  ports:
    - name: http-web
      port: 3000
      targetPort: 3000 
      nodePort: 30080

