apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus-pv
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-stack-kube-prom-prometheus
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/share/nfs/storage/prometheus"

