apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector: 
    app.kubernetes.io/name: prometheus
  type: NodePort  
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090 
      nodePort: 30701

