version: '3'

services:
  nginx:
    image: nginx:stable
    container_name: nginx_reverse
    ports:
      - "8080:80"
      - "8043:443"
    volumes:
      - /docker/server/nginx:/etc/nginx/conf.d
      - /docker/server/nginx/certbot/conf:/etc/letsencrypt
      - /docker/server/nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /docker/server/nginx/certbot/conf:/etc/letsencrypt
      - /docker/server/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
