apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: rentahouse
  labels:
    app: apigateway-service
spec:
  selector: 
    app: apigateway
  type: NodePort  
  ports:
    - name: "apigateway-metrics"
      port: 9091
      targetPort: 9091
      nodePort: 31000

