version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.37.6
    ports:
      - 17090:9090
    volumes:
      - /share/nfs/supervision/prometheus/data:/prometheus
      - /share/nfs/supervision/prometheus/config:/etc/prometheus

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    ports:
      - 17091:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  grafana:
    image: grafana/grafana:9.4.3
    ports:
      - 17092:3000
    volumes:
      - /share/nfs/supervision/grafana/data:/var/lib/grafana
      - /share/nfs/supervision/grafana/config:/etc/grafana/provisioning

