---
# tasks file for roles/mysql-exporter

- name: check if mysql exporter exist
  stat:
    path: "{{ mysqld_exporter_bin }}"
  register: __check_mysqld_exporter_present

- name: create mysql exporter user
  user:
    name: "{{ mysqld_exporter_user }}"
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create mysql exporter config dir
  file:
    path: "{{ mysqld_exporter_dir_conf }}"
    state: directory
    owner: "{{ mysqld_exporter_user }}"
    group: "{{ mysqld_exporter_group }}"

- name: if mysql exporter exist get version
  shell: "cat /etc/systemd/system/mysqld_exporter.service | grep Version | sed s/'.*Version '//g"
  when: __check_mysqld_exporter_present.stat.exists == true
  changed_when: false
  register: __get_mysqld_exporter_version

- name: download and unzip mysql exporter if not exist
  unarchive:
    src: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: move the binary to the final destination
  copy:
    src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/mysqld_exporter"
    dest: "{{ mysqld_exporter_bin }}"
    owner: "{{ mysqld_exporter_user }}"
    group: "{{ mysqld_exporter_group }}"
    mode: 0755
    remote_src: yes
  when: __check_mysqld_exporter_present.stat.exists == false or not __get_mysqld_exporter_version.stdout == mysqld_exporter_version

- name: clean
  file:
    path: /tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/
    state: absent

- name: install service
  template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_mysqld_exporter

    #- meta: flush_handlers

- name: service always started
  systemd:
    name: mysqld_exporter
    state: started
    enabled: yes

