apiVersion: apps/v1
kind: Deployment
metadata:
  name: wslocuser-deployment
  namespace: rentahouse
  labels:
    app.kubernetes.io/component: web-service
    app.kubernetes.io/part-of: rentahouse
spec:
  selector:
    matchLabels:
      app: wslocuser
  replicas: 2
  template:
    metadata:
      labels:
        app: wslocuser
    spec:
      containers:
      - name: wslocuser
        image: registry.gitlab.com/kilroywashere.devops/wslocuser/main
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "gcp"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 120
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 120
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "50Mi"
