apiVersion: v1
kind: Service
metadata:
  name: wslocuser-service
  namespace: rentahouse
spec:
  selector: 
    app: wslocuser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
