global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
- target_matchers:
  - alertname = InfoInhibitor
receivers:
- name: "null"
- name: "gmail-notifications-warning"
  email_configs:
  - to: yourmemail@gmail.com
    from: yourmemail@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: yourmemail@gmail.com
    auth_identity: yourmemail@gmail.com
    auth_password: yourpassword
    send_resolved: true
- name: "gmail-notifications-critical"
  email_configs:
  - to: kilroywashere.devops@gmail.com
    from: yourmemail@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: yourmemail@gmail.com
    auth_identity: yourmemail@gmail.com
    auth_password: yourpassword
    send_resolved: true
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: "null"
  repeat_interval: 12h
  routes:
  - matchers:
    - alertname = "Watchdog"
    receiver: "null"
  - match:
      severity: "warning"
    receiver: "gmail-notifications-warning"
  - match:
      severity: "critical"
    receiver: "gmail-notifications-critical"
templates:
- /etc/alertmanager/config/*.tmpl

