global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []

rule_files: []

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['supervision-app_prometheus:9090']
  - job_name: 'grafana'
    static_configs:
    - targets: ['supervision-app_grafana:3000']
  - job_name: 'nodeexporter'
    static_configs:
    - targets: ['supervision-app_nodeexporter:9100']
