apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rabbitmq-pvc
  namespace: rabbitmq-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

