version: "3.8"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=abcd4ABCD
      - MARIADB_DATABASE=glpi
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=glpi

#GLPI Container
  glpi:
    build: ./image
    container_name : glpi
    hostname: glpi
    ports:
      - "8090:80"
